# Generated by Django 3.2.6 on 2021-10-06 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
                ('name', models.CharField(max_length=144, verbose_name='Nombre')),
                ('slug_name', models.SlugField(max_length=40, unique=True, verbose_name='Slug field')),
                ('about', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='boxes/pictures', verbose_name='Imagen')),
                ('rides_offered', models.PositiveIntegerField(default=0, verbose_name='Viajes ofrecidos')),
                ('rides_taken', models.PositiveIntegerField(default=0, verbose_name='Viajes tomados')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified if is official communites', verbose_name='Verificador')),
                ('is_public', models.BooleanField(default=False, help_text='If is public or private', verbose_name='Publico')),
                ('is_limited', models.BooleanField(default=False, verbose_name='Limites de miembros')),
                ('member_limited', models.PositiveIntegerField(default=0, verbose_name='Cantidad del limite')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_create_for', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_update_for', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificacor')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'date_created',
                'abstract': False,
            },
        ),
    ]
